name: CI
on: push
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build Image
      run: ./gradlew build
    - name: Release Version
      id: release
      if: ${{ github.ref_name == 'master' || startsWith(github.ref_name, 'release/') }}
      run: echo "RELEASE_VERSION=`./gradlew -q version`" >> "$GITHUB_OUTPUT"
    - name: Print Version
      if: ${{ steps.release.outputs.RELEASE_VERSION }}
      env:
        RELEASE_VERSION: ${{ steps.release.outputs.RELEASE_VERSION }}
      run: echo "Release $RELEASE_VERSION"
