name: CI
on: push
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build Image
      run: ./gradlew -PcurrentRevision=`git rev-parse --short=10 HEAD` build
    - name: List Tags
      id: tags
      run: echo "HEAD=`git tag --points-at HEAD | tr '\n' ' '`" >> "$GITHUB_OUTPUT"
    - name: Push Image
      id: release
      if: ${{ !steps.tags.outputs.HEAD && (github.ref_name == 'master' || startsWith(github.ref_name, 'release/')) }}
      env:
        DOCKERHUB_SECRET: ${{ secrets.DOCKERHUB_SECRET }}
      run: echo "RELEASE_VERSION=`./gradlew -q version`" >> "$GITHUB_OUTPUT" && ./gradlew -PdockerhubUser=boolivar -PdockerhubPass=$DOCKERHUB_SECRET dockerPushImage --dry-run
    - name: Tag Release
      if: ${{ steps.release.outputs.RELEASE_VERSION }}
      env:
        RELEASE_VERSION: ${{ steps.release.outputs.RELEASE_VERSION }}
      run: |
        git config user.name "GitHub Action" && git config user.email "2944216+boolivar@users.noreply.github.com"
        git tag -m "Release $RELEASE_VERSION" -a "$RELEASE_VERSION-`git tag -l "$RELEASE_VERSION-*" | wc -l`" && git tag -f $RELEASE_VERSION && git push --force --tags
